// Dev-only fixture data so the site can render without a NOTION_TOKEN.
// Enabled by setting SITE_FIXTURE=1. Hero/About/Contact copy mirrors the real
// Notion content; the list sections are representative samples, not the live data.
import type { SiteData } from './types';

export const fixtureSiteData: SiteData = {
  profile: {
    hero: {
      id: 'fixture-hero',
      section: 'Hero',
      headline: 'Yulan Galagoda',
      content:
        'Cyber security engineer and AI researcher defending everything from enterprise networks to intelligent machines. BSc (Hons) Computer Security, First Class. Currently reading MSc Artificial Intelligence at the University of Plymouth.',
      imagePath: null,
      order: 1,
    },
    about: {
      id: 'fixture-about',
      section: 'About',
      headline: 'About',
      content:
        "I work at the intersection of cyber security and machine learning. My MSc dissertation explores adversarial training for deep-learning intrusion detection on the Controller Area Network (CAN bus), the nervous system of every modern car, using the CICIoV2024 dataset and techniques from the Adversarial Robustness Toolbox.<br><br>Before Plymouth, I built NetEAGLE, a Raspberry Pi-based network gateway combining a Flask API, mobile app, Nmap, UFW and Suricata IDPS into a single home-network defender. Earlier still, I served as a Cyber Security Engineer Executive at Union Assurance PLC and an Associate Engineer at Lanka Communications.<br><br>When I'm not reading papers I'm cataloguing antiques in The Reliquary, documenting Sri Lankan and global recipes in Rampe, and refining the database that powers this site.",
      imagePath: null,
      order: 2,
    },
    contact: {
      id: 'fixture-contact',
      section: 'Contact',
      headline: 'Get in touch',
      content:
        'Open to research collaborations and consultations in IoV security, adversarial ML, and IDS evaluation.<br><br>Email: [yulangalagoda1@gmail.com](mailto:yulangalagoda1@gmail.com)<br>Location: Plymouth, United Kingdom',
      imagePath: null,
      order: 3,
    },
    siteMeta: undefined,
  },
  socials: [
    { id: 'fixture-social-1', name: 'GitHub', url: 'https://github.com/', handle: 'yulan', icon: 'github', order: 1 },
    { id: 'fixture-social-2', name: 'LinkedIn', url: 'https://www.linkedin.com/', handle: 'yulan-galagoda', icon: 'linkedin', order: 2 },
  ],
  experience: [
    {
      id: 'fixture-exp-1',
      role: 'Cyber Security Engineer Executive',
      organisation: 'Union Assurance PLC',
      description: 'Security operations and engineering for a national insurer.',
      highlights: [
        'Ran vulnerability management and remediation across the corporate estate.',
        'Tuned SIEM detections and led incident triage.',
      ],
      location: 'Colombo, Sri Lanka',
      technologies: ['SIEM', 'Vulnerability Management', 'Incident Response'],
      type: 'Full-time',
      startDate: '2023-01-01',
      endDate: '2024-08-01',
      current: false,
      order: 1,
    },
    {
      id: 'fixture-exp-2',
      role: 'Associate Engineer',
      organisation: 'Lanka Communications',
      description: 'Network and security engineering for enterprise customers.',
      highlights: ['Deployed and maintained enterprise firewalls and VPNs.'],
      location: 'Colombo, Sri Lanka',
      technologies: ['Networking', 'Firewalls', 'VPN'],
      type: 'Full-time',
      startDate: '2021-06-01',
      endDate: '2022-12-01',
      current: false,
      order: 2,
    },
  ],
  education: [
    {
      id: 'fixture-edu-1',
      qualification: 'MSc Artificial Intelligence',
      institution: 'University of Plymouth',
      field: 'Artificial Intelligence',
      grade: undefined,
      description: 'Dissertation: adversarial training for CAN-bus intrusion detection.',
      highlights: [],
      startDate: '2025-09-01',
      endDate: undefined,
      current: true,
      order: 1,
    },
    {
      id: 'fixture-edu-2',
      qualification: 'BSc (Hons) Computer Security',
      institution: 'University of Plymouth',
      field: 'Computer Security',
      grade: 'First Class',
      description: undefined,
      highlights: [],
      startDate: '2022-09-01',
      endDate: '2025-06-01',
      current: false,
      order: 2,
    },
  ],
  skills: [
    { id: 'fixture-skill-1', name: 'Python', category: 'Languages', featured: true, proficiency: 'Expert', visible: true, order: 1 },
    { id: 'fixture-skill-2', name: 'Adversarial ML', category: 'AI/ML', featured: true, proficiency: 'Advanced', visible: true, order: 2 },
    { id: 'fixture-skill-3', name: 'Suricata IDS', category: 'Security', featured: true, proficiency: 'Advanced', visible: true, order: 3 },
    { id: 'fixture-skill-4', name: 'PyTorch', category: 'AI/ML', featured: true, proficiency: 'Advanced', visible: true, order: 4 },
    { id: 'fixture-skill-5', name: 'Network Security', category: 'Security', featured: true, proficiency: 'Expert', visible: true, order: 5 },
  ],
  certifications: [
    {
      id: 'fixture-cert-1',
      name: 'Sample Security Certification',
      issuer: 'Issuing Body',
      category: 'Security',
      issued: '2024-05-01',
      expires: undefined,
      hasExpiry: false,
      credentialId: 'ABC-1234',
      verifyUrl: undefined,
      order: 1,
    },
  ],
  projects: [
    {
      id: 'fixture-proj-1',
      slug: 'can-bus-adversarial-ids',
      name: 'CAN-Bus Adversarial IDS',
      tagline: 'Adversarially robust intrusion detection for connected vehicles',
      description:
        'MSc dissertation project: deep-learning IDS for the Controller Area Network hardened with adversarial training, evaluated on CICIoV2024.',
      highlights: [
        'Adversarial Robustness Toolbox attack/defence pipeline.',
        'Benchmarked clean vs. robust accuracy across attack budgets.',
      ],
      role: 'Researcher',
      status: 'In progress',
      type: 'Research',
      technologies: ['Python', 'PyTorch', 'ART', 'CICIoV2024'],
      liveUrl: undefined,
      githubUrl: undefined,
      reportUrl: undefined,
      featured: true,
      year: '2026-01-01',
      order: 1,
    },
    {
      id: 'fixture-proj-2',
      slug: 'neteagle',
      name: 'NetEAGLE',
      tagline: 'Raspberry Pi home-network defender',
      description:
        'A network gateway combining a Flask API, mobile app, Nmap, UFW and Suricata IDPS into a single home-network security appliance.',
      highlights: ['Final-year BSc project.'],
      role: 'Creator',
      status: 'Complete',
      type: 'Engineering',
      technologies: ['Raspberry Pi', 'Flask', 'Suricata', 'Nmap', 'UFW'],
      liveUrl: undefined,
      githubUrl: undefined,
      reportUrl: undefined,
      featured: true,
      year: '2025-01-01',
      order: 2,
    },
  ],
  research: [
    {
      id: 'fixture-res-1',
      title: 'Adversarial Training for CAN-Bus Intrusion Detection',
      authors: 'Yulan Galagoda',
      venue: undefined,
      institution: 'University of Plymouth',
      supervisor: undefined,
      status: 'In progress',
      type: 'MSc Dissertation',
      abstract:
        'Evaluating adversarial training as a defence for deep-learning intrusion detection systems on in-vehicle networks.',
      keywords: ['CAN bus', 'IDS', 'adversarial ML'],
      published: undefined,
      doiUrl: undefined,
      pdfUrl: undefined,
      order: 1,
    },
  ],
  sideWorlds: [
    {
      id: 'fixture-side-1',
      name: 'The Reliquary',
      tagline: 'A private catalogue of antiques',
      description: 'Cataloguing and researching antiques and curios.',
      type: 'Collection',
      status: 'Active',
      icon: undefined,
      externalUrl: undefined,
      internalUrl: undefined,
      order: 1,
    },
    {
      id: 'fixture-side-2',
      name: 'Rampe',
      tagline: 'Sri Lankan and global recipes',
      description: 'Documenting family recipes and food history.',
      type: 'Recipes',
      status: 'Active',
      icon: undefined,
      externalUrl: undefined,
      internalUrl: undefined,
      order: 2,
    },
  ],
  badges: [],
  logoPath: null,
  portraitPath: null,
};
